name: RandomTP
main: org.Rimuru.random.RTP
version: 1.0
api-version: 1.21
commands:
  rtp:
    description: Randomly teleports you
    usage: /rtp
    permission: rtp.use

  rtpcd:
    description: Check RTP cooldown
    usage: /rtpcd
    permission: op

  changecd:
    description: Change the RTP cooldown time.
    usage: /changecd <seconds>
    permission: op

permissions:
  rtp.use:
    description: Allows using /rtp
    default: op